/**
 * Deterministic PDF fixtures for the PDF reading, structure and annotation tests.
 *
 * Provenance: every byte is generated by this file (no third-party content), so the
 * fixtures are redistributable under the repository licence. They are intentionally
 * small, uncompressed PDF 1.7 files that use only the standard Helvetica fonts so the
 * real pinned pdfjs-dist build can parse them in Node without network access.
 *
 * Fixture catalogue:
 * - taggedReport: Tagged PDF with /Artifact Pagination Header/Footer/PageNum marked
 *   content, H1/H2/P/L/LI/Table/TH/TD/Link/Figure structure, /Lang, page labels and a
 *   logical structure order that differs from content-stream order. Page 2 also has one
 *   unowned (neither tagged nor artifact) text run; page 3 has a real heading whose text
 *   equals the running header.
 * - untaggedReport: Untagged pages with a repeated running header, "Page N of M" footers,
 *   repeated body text in a body position, and a two-column page.
 * - rotatedPage: Untagged single page with /Rotate 90.
 * - scannedPage: Image-only page without any text.
 * - ligatureAndHyphenation: fi/fl glyphs via a Differences encoding, a line-end
 *   hyphenated word, Latin-1 accents and repeated phrases for ambiguity tests.
 * - longDocument: n untagged pages with running headers and "- n -" footers.
 * - linkedDocument: internal GoTo and external URI links, plus a JavaScript link, a
 *   file: URI link and a JavaScript OpenAction that must never run or be followed.
 */

type PageSpec = {
  width?: number;
  height?: number;
  rotate?: number;
  content: string;
  annots?: string[];
  structParents?: number;
  extraResources?: string;
  extra?: string;
};

function pdfString(value: string): string {
  let output = '';
  for (const char of value) {
    const code = char.codePointAt(0)!;
    if (char === '(' || char === ')' || char === '\\') output += `\\${char}`;
    else if (code < 32 || code > 126) output += `\\${(code & 0xff).toString(8).padStart(3, '0')}`;
    else output += char;
  }
  return `(${output})`;
}

class PdfBuilder {
  private objects: string[] = [];

  reserve(): number {
    this.objects.push('null');
    return this.objects.length;
  }

  set(id: number, body: string): number {
    this.objects[id - 1] = body;
    return id;
  }

  add(body: string): number {
    return this.set(this.reserve(), body);
  }

  stream(content: string, dictionary = ''): number {
    return this.add(`<<${dictionary}/Length ${content.length}>>\nstream\n${content}\nendstream`);
  }

  build(rootId: number, infoId?: number): Uint8Array {
    let output = '%PDF-1.7\n%\xe2\xe3\xcf\xd3\n';
    const offsets: number[] = [];
    this.objects.forEach((body, index) => {
      offsets.push(output.length);
      output += `${index + 1} 0 obj\n${body}\nendobj\n`;
    });
    const xref = output.length;
    output += `xref\n0 ${this.objects.length + 1}\n0000000000 65535 f \n`;
    for (const offset of offsets) output += `${String(offset).padStart(10, '0')} 00000 n \n`;
    output += `trailer\n<</Size ${this.objects.length + 1}/Root ${rootId} 0 R${
      infoId ? `/Info ${infoId} 0 R` : ''
    }>>\nstartxref\n${xref}\n%%EOF\n`;
    return Uint8Array.from(output, (char) => char.charCodeAt(0) & 0xff);
  }
}

const FONT =
  '<</Type/Font/Subtype/Type1/BaseFont/Helvetica/Encoding<</Type/Encoding/BaseEncoding/WinAnsiEncoding/Differences[1/fi 2/fl]>>>>';
const BOLD = '<</Type/Font/Subtype/Type1/BaseFont/Helvetica-Bold/Encoding/WinAnsiEncoding>>';

function text(x: number, y: number, size: number, value: string, font = 'F1'): string {
  return `BT /${font} ${size} Tf ${x} ${y} Td ${pdfString(value)} Tj ET`;
}

/** Text with raw (already escaped) string bytes, for glyph codes such as \001 (fi). */
function rawText(x: number, y: number, size: number, raw: string, font = 'F1'): string {
  return `BT /${font} ${size} Tf ${x} ${y} Td (${raw}) Tj ET`;
}

function marked(tag: string, mcid: number, body: string): string {
  return `/${tag} <</MCID ${mcid}>> BDC\n${body}\nEMC`;
}

function artifact(subtype: 'Header' | 'Footer' | 'PageNum', body: string): string {
  return `/Artifact <</Type/Pagination/Subtype/${subtype}>> BDC\n${body}\nEMC`;
}

function buildDocument(
  builder: PdfBuilder,
  pages: PageSpec[],
  options: { catalogExtra?: string; title?: string; beforeBuild?: (pageIds: number[]) => void } = {},
): Uint8Array {
  const pagesId = builder.reserve();
  const fontId = builder.add(FONT);
  const boldId = builder.add(BOLD);
  const pageIds = pages.map(() => builder.reserve());
  pages.forEach((page, index) => {
    const contentId = builder.stream(page.content);
    builder.set(
      pageIds[index],
      `<</Type/Page/Parent ${pagesId} 0 R/MediaBox[0 0 ${page.width ?? 612} ${page.height ?? 792}]${
        page.rotate ? `/Rotate ${page.rotate}` : ''
      }/Resources<</Font<</F1 ${fontId} 0 R/F2 ${boldId} 0 R>>${page.extraResources ?? ''}>>/Contents ${contentId} 0 R${
        page.annots?.length ? `/Annots[${page.annots.join(' ')}]` : ''
      }${page.structParents === undefined ? '' : `/StructParents ${page.structParents}`}${page.extra ?? ''}>>`,
    );
  });
  builder.set(pagesId, `<</Type/Pages/Kids[${pageIds.map((id) => `${id} 0 R`).join(' ')}]/Count ${pages.length}>>`);
  options.beforeBuild?.(pageIds);
  const infoId = options.title
    ? builder.add(`<</Title ${pdfString(options.title)}/Producer (A11y Notebook fixtures)>>`)
    : undefined;
  const catalogId = builder.add(`<</Type/Catalog/Pages ${pagesId} 0 R${options.catalogExtra ?? ''}>>`);
  return builder.build(catalogId, infoId);
}

/** Three-page tagged report. Logical order on page 1 intentionally differs from paint order. */
export function taggedReport(): Uint8Array {
  const builder = new PdfBuilder();
  const structRoot = builder.reserve();
  const documentElement = builder.reserve();
  const parentTree = builder.reserve();
  const linkAnnot = builder.reserve();
  const elements: { id: number; role: string; parent: number; page?: number; own: string; extra: string }[] = [];
  const element = (role: string, parent: number, page: number | undefined, own: string, extra = '') => {
    const id = builder.reserve();
    elements.push({ id, role, parent, page, own, extra });
    return id;
  };
  const h1 = element('H1', documentElement, 0, '0');
  const intro = element('P', documentElement, 0, '1');
  const second = element('P', documentElement, 0, '2');
  const list = element('L', documentElement, 0, '');
  const li1 = element('LI', list, 0, '');
  const lbody1 = element('LBody', li1, 0, '3');
  const li2 = element('LI', list, 0, '');
  const lbody2 = element('LBody', li2, 0, '4');
  const french = element('P', documentElement, 0, '5', '/Lang (fr-FR)');
  const h2 = element('H2', documentElement, 1, '0');
  const table = element('Table', documentElement, 1, '', '/A<</O/Table/Summary (Scores by person)>>');
  const tr1 = element('TR', table, 1, '');
  const thName = element('TH', tr1, 1, '1', '/ID (hdr-name)/A<</O/Table/Scope/Column>>');
  const thScore = element('TH', tr1, 1, '2', '/ID (hdr-score)/A<</O/Table/Scope/Column>>');
  const tr2 = element('TR', table, 1, '');
  const tdName = element('TD', tr2, 1, '3', '/A<</O/Table/Headers[(hdr-name)]>>');
  const tdScore = element('TD', tr2, 1, '4', '/A<</O/Table/Headers[(hdr-score)]>>');
  const tr3 = element('TR', table, 1, '');
  const tdSpan = element('TD', tr3, 1, '5', '/A<</O/Table/ColSpan 2/Headers[(hdr-name) (hdr-score)]>>');
  const linkPara = element('P', documentElement, 1, '');
  const link = element('Link', linkPara, 1, `6 <</Type/OBJR/Obj ${linkAnnot} 0 R>>`);
  const figure = element(
    'Figure',
    documentElement,
    1,
    '7',
    '/Alt (Bar chart showing Ada scoring 10)/A<</O/Layout/BBox[72 300 272 400]>>',
  );
  const h2b = element('H2', documentElement, 2, '0');
  const closing = element('P', documentElement, 2, '1');

  const pagesId = builder.reserve();
  const fontId = builder.add(FONT);
  const boldId = builder.add(BOLD);
  const pageIds = [builder.reserve(), builder.reserve(), builder.reserve()];
  for (const item of elements) {
    const children = elements.filter((child) => child.parent === item.id).map((child) => `${child.id} 0 R`);
    const kids = [...children, item.own].filter(Boolean).join(' ');
    builder.set(
      item.id,
      `<</Type/StructElem/S/${item.role}/P ${item.parent} 0 R${
        item.page === undefined ? '' : `/Pg ${pageIds[item.page]} 0 R`
      }/K [${kids}]${item.extra}>>`,
    );
  }
  const documentKids = elements.filter((item) => item.parent === documentElement).map((item) => `${item.id} 0 R`);
  builder.set(
    documentElement,
    `<</Type/StructElem/S/Document/P ${structRoot} 0 R/K [${documentKids.join(' ')}]/Lang (en-GB)>>`,
  );
  builder.set(
    structRoot,
    `<</Type/StructTreeRoot/K ${documentElement} 0 R/ParentTree ${parentTree} 0 R/ParentTreeNextKey 4>>`,
  );
  const refs = (ids: number[]) => `[${ids.map((id) => `${id} 0 R`).join(' ')}]`;
  builder.set(
    parentTree,
    `<</Nums[0 ${refs([h1, intro, second, lbody1, lbody2, french])} 1 ${refs([
      h2,
      thName,
      thScore,
      tdName,
      tdScore,
      tdSpan,
      link,
      figure,
    ])} 2 ${refs([h2b, closing])} 3 ${link} 0 R]>>`,
  );
  const pagination = (n: number) =>
    [
      artifact('Header', text(72, 750, 9, 'Quarterly Accessibility Report')),
      artifact('Footer', text(72, 40, 9, 'Confidential draft')),
      artifact('PageNum', text(520, 40, 9, String(n))),
    ].join('\n');
  const contents = [
    [
      pagination(1),
      marked('P', 2, text(72, 600, 12, 'Second paragraph follows the introduction.')),
      marked('H1', 0, text(72, 700, 20, 'Accessible Reading', 'F2')),
      marked('P', 1, text(72, 660, 12, 'Introduction paragraph for the report.')),
      marked('LBody', 3, text(90, 560, 12, 'First list item')),
      marked('LBody', 4, text(90, 540, 12, 'Second list item')),
      marked('P', 5, text(72, 500, 12, 'Bonjour le monde')),
    ],
    [
      pagination(2),
      marked('H2', 0, text(72, 700, 16, 'Results', 'F2')),
      marked('TH', 1, text(72, 660, 12, 'Name', 'F2')),
      marked('TH', 2, text(272, 660, 12, 'Score', 'F2')),
      marked('TD', 3, text(72, 640, 12, 'Ada')),
      marked('TD', 4, text(272, 640, 12, '10')),
      marked('TD', 5, text(72, 620, 12, 'Total spans both columns')),
      marked('Link', 6, text(72, 580, 12, 'Visit the example site')),
      marked('Figure', 7, text(72, 350, 12, 'chart')),
      text(72, 200, 10, 'Unowned note printed without tags.'),
    ],
    [
      pagination(3),
      marked('H2', 0, text(72, 700, 16, 'Quarterly Accessibility Report', 'F2')),
      marked('P', 1, text(72, 660, 12, 'Closing remarks end the document.')),
    ],
  ];
  contents.forEach((lines, index) => {
    const contentId = builder.stream(lines.join('\n'));
    builder.set(
      pageIds[index],
      `<</Type/Page/Parent ${pagesId} 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 ${fontId} 0 R/F2 ${boldId} 0 R>>>>/Contents ${contentId} 0 R/StructParents ${index}${
        index === 1 ? `/Annots[${linkAnnot} 0 R]/Tabs/S` : ''
      }>>`,
    );
  });
  builder.set(
    linkAnnot,
    '<</Type/Annot/Subtype/Link/Rect[70 575 220 592]/Border[0 0 0]/StructParent 3/A<</S/URI/URI (https://example.com/report)>>>>',
  );
  builder.set(pagesId, `<</Type/Pages/Kids[${pageIds.map((id) => `${id} 0 R`).join(' ')}]/Count 3>>`);
  const info = builder.add('<</Title (Quarterly Accessibility Report)/Producer (A11y Notebook fixtures)>>');
  const catalog = builder.add(
    `<</Type/Catalog/Pages ${pagesId} 0 R/StructTreeRoot ${structRoot} 0 R/MarkInfo<</Marked true>>/Lang (en-GB)/PageLabels<</Nums[0<</S/r>>2<</S/D/St 1>>]>>>>`,
  );
  return builder.build(catalog, info);
}

/** Untagged report: running header + "Page N of M" footer + repeated body text; page 3 is two-column. */
export function untaggedReport(pageCount = 5): Uint8Array {
  const pages: PageSpec[] = [];
  for (let index = 1; index <= pageCount; index += 1) {
    const lines = [
      text(72, 752, 9, 'Field Notes Annual Review'),
      text(72, 700, 16, index === 1 ? 'Introduction' : `Chapter ${index}`, 'F2'),
      text(72, 660, 12, 'Summary'),
      text(72, 640, 12, `Body text unique to page ${index}.`),
      text(250, 40, 9, `Page ${index} of ${pageCount}`),
    ];
    if (index === 3) {
      lines.push(text(72, 600, 11, 'Left column first line.'));
      lines.push(text(72, 586, 11, 'Left column second line.'));
      lines.push(text(320, 600, 11, 'Right column first line.'));
      lines.push(text(320, 586, 11, 'Right column second line.'));
    }
    pages.push({ content: lines.join('\n') });
  }
  return buildDocument(new PdfBuilder(), pages, { title: 'Field Notes Annual Review' });
}

export function rotatedPage(): Uint8Array {
  return buildDocument(new PdfBuilder(), [
    {
      rotate: 90,
      content: [text(72, 700, 14, 'Rotated heading text'), text(72, 670, 12, 'Rotated body sentence.')].join('\n'),
    },
  ]);
}

export function scannedPage(): Uint8Array {
  const builder = new PdfBuilder();
  const image = builder.stream(
    'ffffff000000000000ffffff>',
    '/Type/XObject/Subtype/Image/Width 2/Height 2/ColorSpace/DeviceRGB/BitsPerComponent 8/Filter/ASCIIHexDecode',
  );
  return buildDocument(builder, [
    { content: 'q 400 0 0 500 100 150 cm /Im1 Do Q', extraResources: `/XObject<</Im1 ${image} 0 R>>` },
  ]);
}

export function ligatureAndHyphenation(): Uint8Array {
  return buildDocument(new PdfBuilder(), [
    {
      content: [
        rawText(72, 700, 12, 'The \\001rst \\002ow of ef\\001cient work.'),
        text(72, 680, 12, 'Reading improves accessi-'),
        text(72, 666, 12, 'bility for everyone.'),
        text(72, 640, 12, 'Caf\u00e9 cr\u00e8me \u0097 na\u00efve r\u00e9sum\u00e9.'),
        text(72, 620, 12, 'the cat sat. the cat ran. the dog sat.'),
      ].join('\n'),
    },
  ]);
}

export function longDocument(pageCount: number): Uint8Array {
  const pages: PageSpec[] = [];
  for (let index = 1; index <= pageCount; index += 1) {
    pages.push({
      content: [
        text(72, 752, 9, 'Long Document Running Title'),
        text(72, 700, 12, `Paragraph on page ${index} with searchable token p${index}x.`),
        text(300, 30, 9, `- ${index} -`),
      ].join('\n'),
    });
  }
  return buildDocument(new PdfBuilder(), pages, { title: 'Long Document' });
}

export function linkedDocument(): Uint8Array {
  const builder = new PdfBuilder();
  const internal = builder.reserve();
  const external = builder.reserve();
  const script = builder.reserve();
  const unsafe = builder.reserve();
  return buildDocument(
    builder,
    [
      {
        content: [
          text(72, 700, 12, 'Go to the second page'),
          text(72, 680, 12, 'Open the website'),
          text(72, 660, 12, 'Script link'),
          text(72, 640, 12, 'File link'),
        ].join('\n'),
        annots: [`${internal} 0 R`, `${external} 0 R`, `${script} 0 R`, `${unsafe} 0 R`],
      },
      { content: text(72, 700, 12, 'Second page target') },
    ],
    {
      catalogExtra: '/OpenAction<</S/JavaScript/JS (app.alert\\(2\\))>>',
      beforeBuild: (pageIds) => {
        builder.set(
          internal,
          `<</Type/Annot/Subtype/Link/Rect[70 695 250 712]/Border[0 0 0]/A<</S/GoTo/D[${pageIds[1]} 0 R/XYZ 0 792 0]>>>>`,
        );
        builder.set(
          external,
          '<</Type/Annot/Subtype/Link/Rect[70 675 250 692]/Border[0 0 0]/A<</S/URI/URI (https://example.org/docs)>>>>',
        );
        builder.set(
          script,
          '<</Type/Annot/Subtype/Link/Rect[70 655 250 672]/Border[0 0 0]/A<</S/JavaScript/JS (app.alert\\(1\\))>>>>',
        );
        builder.set(
          unsafe,
          '<</Type/Annot/Subtype/Link/Rect[70 635 250 652]/Border[0 0 0]/A<</S/URI/URI (file:///etc/passwd)>>>>',
        );
      },
    },
  );
}
